import h5py
import numpy as np
import os

# This script extracts the conserved variables (density, momentum, energy) from the
# HDF5 files generated by the Athena++ simulations. The results will be printed to 
# the console and saved in a text file.

# When run on the dummy files, the output will serve as the input to calculating ground truth, taken from Athena++ directly,
# to compare against our parallelized implementation.

# HDF5 file format reference: https://github-wiki-see.page/m/PrincetonUniversity/athena/wiki/HDF5-Format

def extract_conserved_variables(file_path):
	if os.path.exists(file_path):
		with h5py.File(file_path, 'r') as f:
			# Athena++ stores the conserved variables in the dataset named 'cons'. The individual variables
			# are each a column, in the order density ("dens") , total energy ("Etot") and momentum ("mom1", "mom2", "mom3").
			
			# Extract the conserved variables dataset
			cons = f['cons'][:]
			
			# Extracting the density, energy and momentum columns;
			density = cons[:, 0]  
			energy = cons[:, 1]  # Assuming momentum is the next three columns
			momentum = cons[:, 2:5]  # Assuming energy is the last column
	else:
		print(f"File {file_path} does not exist. Please check the path and try again.")
		density = None
		energy = None
		momentum = None
		
	return density, energy, momentum

def write_conserved_variables(density, energy, momentum, output_file_path, input_file_path):
		with open(output_file_path, 'w') as f:
			f.write(f'Conserved variables dens, Etot, mom1, mom2, and mom3 extracted from {input_file_path} generated by Athena. \nThis file is the output of ground_truth/ref_script.py.\n')
			f.write("Density:\n")
			f.write(np.array2string(density) + "\n")
			f.write("Momentum:\n")
			f.write(np.array2string(momentum) + "\n")
			f.write("Energy:\n")
			f.write(np.array2string(energy) + "\n")
	
if __name__ == "__main__":
	# Path to the HDF5 file generated by Athena++
	dummy_input_file = '/Users/isabellefite/github/tensor-analysis-for-grmhd/dummy_data/blast.out1.00000.athdf'  # Update this path as needed
	
	# Path to the output text file
	dummy_output_file = '/Users/isabellefite/github/tensor-analysis-for-grmhd/blast.out1.00000.txt'

	density, energy, momentum = extract_conserved_variables(dummy_input_file)
		
	# Print the extracted variables
	print("Density:", density)
	print("Momentum:", momentum)
	print("Energy:", energy)

	write_conserved_variables(density, energy, momentum, dummy_output_file, dummy_input_file)

