import h5py
import numpy as np
import os

# This script extracts the conserved variables (density, momentum, energy) from the
# HDF5 files generated by the Athena++ simulations. The results will be printed to 
# the console and saved in a text file.

# When run on the dummy files, the output will serve as the input to calculating ground truth, taken from Athena++ directly,
# to compare against our parallelized implementation.

# HDF5 file format reference: https://github-wiki-see.page/m/PrincetonUniversity/athena/wiki/HDF5-Format

def extract_variables(timestep):
    # Target the separate output files generated by athinput
    script_dir = os.path.dirname(os.path.abspath(__file__))
    base_path = os.path.join(script_dir, "..", "..", "dummy_data")
    cons_file = os.path.join(base_path, f'blast.out1.{timestep}.athdf')
    mag_file  = os.path.join(base_path, f'blast.out2.{timestep}.athdf')
    prim_file = os.path.join(base_path, f'blast.out3.{timestep}.athdf')
    
    if not (os.path.exists(cons_file) and os.path.exists(mag_file) and os.path.exists(prim_file)):
        print("One or more files for timestep {timestep} do not exist in dummy_data/. Please check paths.")
        return None, None, None, None
    
    data = {}

    # 1. Extract Conserved Variables (D, M1, M2, M3, E)
    with h5py.File(cons_file, 'r') as f_cons:
        # cons shape: [Level, Variable, Z, Y, X]
        cons = f_cons['cons'][:]
        data['D']  = cons[0, :, 0, :, :]    # Index 0: Density
        data['E']  = cons[1, :, 0, :, :]    # Index 1: Total Energy (was 4.125)
        data['M1'] = cons[2, :, 0, :, :]    # Index 2: Momentum X
        data['M2'] = cons[3, :, 0, :, :]    # Index 3: Momentum Y
        data['M3'] = cons[4, :, 0, :, :]    # Index 4: Momentum Z (should be 0)
        
    # 2. Extract Cell-Centered Magnetic Field (B1, B2, B3)
    with h5py.File(mag_file, 'r') as f_mag:
        # print("Keys inside this HDF5 file:", list(f_mag.keys()))
        data['Bcc'] = f_mag['hydro'][:, :, 0, :, :]

    # 3. Extract Primitive Variables (rho, P, v1, v2, v3)
    with h5py.File(prim_file, 'r') as f_prim:
        prim = f_prim['prim'][:]
        data['rho'] = prim[0, :, 0, :, :]      # Index 0: Rest-mass density
        data['P']   = prim[1, :, 0, :, :]      # Index 1: Gas pressure
        data['v1']  = prim[2, :, 0, :, :]      # Velocity X
        data['v2']  = prim[3, :, 0, :, :]      # Velocity Y
            
    return data


def write_variables(data, output_file_path):			
    with open(output_file_path, 'w') as f:
        f.write("Athena++ Extracted Ground Truth Data\n")
        f.write("====================================\n\n")
        
        f.write("--- CONSERVED VARIABLES ---\n")
        f.write("Density (D):\n")
        f.write(np.array2string(data['D']) + "\n\n")
        f.write("Momentum (M1, M2, M3):\n")
        f.write(np.array2string(data['M1']) + "\n\n")
        f.write(np.array2string(data['M2']) + "\n\n")
        f.write(np.array2string(data['M3']) + "\n\n")
        f.write("Total Energy (E):\n")
        f.write(np.array2string(data['E']) + "\n\n")

        f.write("--- MAGNETIC FIELD ---\n")
        f.write("Cell-Centered B-field (B1, B2, B3):\n")
        f.write(np.array2string(data['Bcc']) + "\n\n")  

        f.write("--- PRIMITIVE VARIABLES ---\n")
        f.write("Rest-mass Density (rho):\n")
        f.write(np.array2string(data['rho']) + "\n\n")
        f.write("Gas Pressure (P):\n")
        f.write(np.array2string(data['P']) + "\n\n")
        f.write("Velocity (v1, v2, v3):\n")
        f.write(np.array2string(data['v1']) + "\n")
        f.write(np.array2string(data['v2']) + "\n")
	
if __name__ == "__main__":
	# Update this to target the specific output timestep you want to analyze
    # (e.g., "00000" for initial conditions, or the final cycle number)
    target_timestep = "00010"
    
    output_file = f'blast_all_extracted_{target_timestep}.txt'
    
    # with h5py.File('../../dummy_data/blast.out1.00010.athdf', 'r') as f:
    #     cons_dataset = f['cons']
    #     print(f"Dataset Shape: {cons_dataset.shape}")
    #     print(f"Dataset Attributes: {list(cons_dataset.attrs.keys())}")
    #     if 'variable_names' in cons_dataset.attrs:
    #         print(f"Variables inside 'cons': {cons_dataset.attrs['variable_names']}")
    
    # Read data
    extracted_data = extract_variables(target_timestep)
    
    if extracted_data is not None:
        # Print shapes to verify extraction
        print(f"Data Extraction Successful for Timestep: {target_timestep}")
        print("-" * 40)
        print(f"Conserved Density (D) shape: {extracted_data['D'].shape}")
        print(f"Conserved Momentum (M1) shape:{extracted_data['M1'].shape}")
        print(f"Conserved Momentum (M2) shape:{extracted_data['M2'].shape}")
        print(f"Conserved Momentum (M3) shape:{extracted_data['M3'].shape}")
        print(f"Conserved Energy (E) shape:  {extracted_data['E'].shape}")
        print(f"Magnetic Field (Bcc) shape:  {extracted_data['Bcc'].shape}")
        print(f"Primitive Density (rho) shape:{extracted_data['rho'].shape}")
        print(f"Primitive Pressure (P) shape: {extracted_data['P'].shape}")
        print(f"Primitive Velocity (v1) shape: {extracted_data['v1'].shape}")
        print(f"Primitive Velocity (v2) shape: {extracted_data['v2'].shape}")
        print("-" * 40)

        # Write data to text file
        write_variables(extracted_data, output_file)
        print(f"All variables successfully written to {output_file}")
